import '../models/models.dart';

const localEatries = [
  TestEatry(
      id: 1,
      image: 'assets/static/eatry-pub.webp',
      name: 'FastFoodie',
      email: 'mgt@fastfoodie.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  TestEatry(
    id: 2,
    image: 'assets/eatries/akif.webp',
    name: 'Akif',
    email: 'mgt@akif.com',
    address: '105 rue Tchoou Ablogame Lome-Togo',
    phone: '000-888-555',
    employees: 10,
    managers: 2,
    owners: 1,
    isPromoted: false,
    isVerified: false,
  ),
  TestEatry(
      id: 3,
      image: 'assets/eatries/ci-gusta.webp',
      name: 'Ci-gusta',
      email: 'mgt@cigusta.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  TestEatry(
      id: 4,
      image: 'assets/eatries/chinese.webp',
      name: 'Dragon Flare',
      email: 'mgt@drgflare.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: false,
      isVerified: false),
  TestEatry(
      id: 5,
      image: 'assets/eatries/golden.webp',
      name: 'Golden Plate',
      email: 'mgt@golden.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  TestEatry(
      id: 6,
      image: 'assets/eatries/mac-do.webp',
      name: "Mc Donald's",
      email: 'mgt@mcdonalds.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  TestEatry(
      id: 6,
      image: 'assets/static/eatry.webp',
      name: 'Michelin',
      email: 'mgt@michelin.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
];
